<?php
declare(strict_types=1);require_once __DIR__.'/bootstrap.php';startSecureSession();
use Models\User;use Core\Database;use Core\Security;
$envFile=__DIR__.'/config/.env';$lock=__DIR__.'/storage/install.lock';$error='';$done=false;
if (!extension_loaded('pdo_mysql')) { $error='PHP-udvidelsen pdo_mysql mangler på serveren.'; }
if (!extension_loaded('openssl')) { $error='PHP-udvidelsen openssl mangler på serveren.'; }
if(is_file($lock)){http_response_code(403);exit('Installationen er allerede gennemført. Fjern kun storage/install.lock, hvis du bevidst vil installere igen.');}
if($_SERVER['REQUEST_METHOD']==='POST' && $error==='')try{
  if(!hash_equals($_SESSION['csrf_token']??'',(string)($_POST['csrf']??'')))throw new RuntimeException('Ugyldig forespørgsel.');
  $host=trim((string)($_POST['db_host']??''));$port=(int)($_POST['db_port']??3306);if($port<1||$port>65535)throw new RuntimeException('Ugyldig databaseport.');$name=trim((string)($_POST['db_name']??''));$dbUser=trim((string)($_POST['db_user']??''));$dbPass=(string)($_POST['db_password']??'');$admin=trim((string)($_POST['admin_username']??''));$pass=(string)($_POST['admin_password']??'');
  if(!preg_match('/^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/',$host))throw new RuntimeException('Ugyldig databasevært.');if(!preg_match('/^[A-Za-z0-9_.-]{1,64}$/',$name))throw new RuntimeException('Ugyldigt databasenavn.');if($dbUser==='')throw new RuntimeException('Databasebrugeren skal udfyldes.');if(!filter_var($admin,FILTER_VALIDATE_EMAIL)&&!preg_match('/^[A-Za-z0-9_.-]{3,100}$/',$admin))throw new RuntimeException('Ugyldigt administratorbrugernavn.');if(strlen($pass)<12)throw new RuntimeException('Administratoradgangskoden skal være mindst 12 tegn.');
 $key=bin2hex(random_bytes(32));$configDir=dirname($envFile);if(!is_dir($configDir)&&!@mkdir($configDir,0750,true))throw new RuntimeException('Mappen config kunne ikke oprettes.');if(!is_writable($configDir))throw new RuntimeException('PHP-processen har ikke skrivetilladelse til mappen config.');$pdo=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 // Resume-safe: a previous attempt may have created the tables before failing.
 $schema=file_get_contents(__DIR__.'/database.sql');foreach(array_filter(array_map('trim',preg_split('/;\s*(?:\r?\n|$)/',$schema))) as $sql)$pdo->exec($sql);
 $existingKey=null;if(is_file($envFile)){foreach(file($envFile,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES) as $line){if(str_starts_with(trim($line),'#')||strpos($line,'=')===false)continue;[$ek,$ev]=explode('=',$line,2);if(trim($ek)==='ENCRYPTION_KEY')$existingKey=trim($ev);}}
 if(is_string($existingKey)&&preg_match('/^[0-9a-fA-F]{64}$/',$existingKey))$key=$existingKey;
   $envValue=static fn(string $value):string=>'"'.str_replace(["\\","\"","\r","\n"],["\\\\","\\\"","",""],$value).'"';$env="DB_HOST=".$envValue($host)."\nDB_PORT={$port}\nDB_NAME=".$envValue($name)."\nDB_USER=".$envValue($dbUser)."\nDB_PASSWORD=".$envValue($dbPass)."\nENCRYPTION_KEY={$key}\nRATE_LIMIT_MAX_REQUESTS=20\nRATE_LIMIT_WINDOW=60\nAPP_ENV=production\nLOG_PATH=".$envValue(__DIR__.'/storage/logs/app.log')."\n";@mkdir(__DIR__.'/storage/logs',0750,true);if(file_put_contents($envFile,$env,LOCK_EX)===false)throw new RuntimeException('Konfigurationsfilen kunne ikke skrives.');@chmod($envFile,0600);
  $_ENV['DB_HOST']=$host;$_ENV['DB_PORT']=(string)$port;$_ENV['DB_NAME']=$name;$_ENV['DB_USER']=$dbUser;$_ENV['DB_PASSWORD']=$dbPass;$_ENV['ENCRYPTION_KEY']=$key;
 $userCount=(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();if($userCount===0)User::createAdmin($admin,$pass);
 @mkdir(__DIR__.'/storage/logs',0750,true);file_put_contents($lock,date('c'),0600);$done=true;
 }catch(PDOException $e){$driverCode=(int)($e->errorInfo[1]??0);if($driverCode===1045||str_contains($e->getMessage(),'[1045]'))$error='Databasen afviser forbindelsen. Kontrollér databasevært, port, brugernavn, adgangskode og at brugeren har adgang fra denne server.';elseif($driverCode===1044||str_contains($e->getMessage(),'[1044]'))$error='Databasebrugeren har ikke adgang til den valgte database.';else{$error='Kunne ikke oprette forbindelse til databasen. Kontrollér forbindelsesoplysningerne.';error_log($e->getMessage());}}catch(Throwable $e){$error=$e->getMessage();}
?><!doctype html><html lang="da"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Multi-Chat – Installation</title><style>body{font-family:system-ui;max-width:760px;margin:40px auto;padding:20px}label{display:block;margin:12px 0}input{width:100%;padding:10px;box-sizing:border-box}.error{background:#fee;padding:12px}.ok{background:#efe;padding:12px}</style></head><body><h1>Installation af Multi-Chat</h1><?php if($done):?><div class="ok">Installationen er gennemført. <a href="public/">Åbn Multi-Chat</a></div><?php else:?><?php if($error):?><div class="error"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf_token']??'',ENT_QUOTES,'UTF-8')?>"><h2>Database</h2><label>Vært<input name="db_host" placeholder="db.example.com eller IP-adresse" required></label><label>Port<input type="number" name="db_port" value="3306" min="1" max="65535" required></label><label>Database<input name="db_name" value="multichat" required></label><label>Bruger<input name="db_user" required></label><label>Adgangskode<input type="password" name="db_password"></label><h2>Administrator</h2><label>Brugernavn<input name="admin_username" required></label><label>Adgangskode (mindst 12 tegn)<input type="password" name="admin_password" required minlength="12"></label><button type="submit">Installér</button></form><?php endif;?></body></html>
